name: TOC Generator
on: push
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOC_TOKEN }}
    - uses: technote-space/toc-generator@v4


    